### PR TITLE
protocol/display: fix Python 3 buffer abstraction

### PR DESCRIPTION
**Pull request by benoit-pierre**
With Python 2, slicing a buffer yield new data, but with Python 3, slicing a memoryview return another memoryview:

```python
> python2 -c 'print buffer(b"12345")[1:3].decode()'
23

> python3 -c 'print(memoryview(b"12345")[1:3].decode())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'memoryview' object has no attribute 'decode'
```

### CODE REVIEW

File: Xlib/protocol/display.py [hunk 1]
```diff
@@ -42,12 +42,41 @@
 from . import event
 
 if PY3:
-    def buffer(object, offset=None, size=None):
+
+    class bytesview(object):
+
+        def __init__(self, data, offset=None, size=None):
```
Comment (vasily-v-ryabov) [inline Xlib/protocol/display.py]: Why not just `offset=0` by default? It saves 2 lines below.

File: Xlib/protocol/display.py [hunk 2]
```diff
@@ -42,12 +42,41 @@
...
+            if offset is None:
+                offset = 0
+            if size is None:
+                size = len(data)-offset
+            if isinstance(data, bytes):
+                view = memoryview(data)
+            elif isinstance(data, bytesview):
+                view = data._view
```
Comment (vasily-v-ryabov) [inline Xlib/protocol/display.py]: All static analyzers will produce a warning for this line. Accessing pseudo-private member of another object can be eliminated with a read-only property `view` for the `_view` field (as an option). Or you may make it public for simplicity.

File: Xlib/protocol/display.py [hunk 3]
```diff
@@ -42,12 +42,41 @@
...
+            else:
+                raise ValueError('unsupported type: %s' % type(data))
```
Comment (vasily-v-ryabov) [inline Xlib/protocol/display.py]: Maybe `raise TypeError('unsupported type: {}'.format(type(data)))` is better and should work on py2.6+.

File: Xlib/protocol/display.py [hunk 4]
```diff
@@ -42,12 +42,41 @@
...
+        def __getitem__(self, key):
+            if isinstance(key, slice):
+                return bytes(self._view[key])
+            return self._view[key]
+
+else:
+
+    def bytesview(data, offset=None, size=None):
+        if not isinstance(data, (bytes, buffer)):
+            raise ValueError('unsupported type: %s' % type(data))
```
Comment (vasily-v-ryabov) [inline Xlib/protocol/display.py]: The same as above.

**Comment by benoit-pierre** [comment]
Thanks for the review, I'll amend.

File: Xlib/protocol/display.py (hunk 3 above)
Comment (benoit-pierre) [inline Xlib/protocol/display.py]: OK, but we don't support 2.6 anymore. In fact, there's a extraneous `view = memoryview(data)` in the Python 2 code that made me realize that `memoryview` is also supported in Python 2, starting with 2.7, so we could further simplify the code by just using one `BytesView` class for all supported Python versions. What do you think?

Comment (vasily-v-ryabov) [inline Xlib/protocol/display.py]: I remember, we don't support py2.6 (just mentioned it because `.format()` is new in 2.6). I like the idea of `BytesView` class.

**Comment by benoit-pierre** [comment]
Unfortunately, `memoryview` behaves differently in Python 2 and 3...

```python
> python2 -c 'print bytes(memoryview(b"12345"))'
<memory at 0x2ae8f7a2f9d0>

> python3 -c 'print(bytes(memoryview(b"12345")))'
b'12345'
```

So I kept the 2 different code paths for Python 2 and 3, and addressed your comments.
